# Original Terra Light Codex texts (written for the mod - not taken from the Earth Light game text).
TL_DESC = {
 'tiamat': ("A broad, boxy line battleship built around four side-mounted triple beam cannons. Each cannon sits in an armoured wall sponson and throws linked volleys of energy bolts across a wide arc, while a ring of small point-defence mounts covers the deck.",
            "Tiamats anchor a battle line and are often chosen as flagships. Their cannons can all bear on a target directly ahead, so they are at their best advancing head-on."),
 'asura':  ("A wedge-prowed battleship carrying a four-barrel railgun turret with an identical twin slung beneath the hull. Rows of missile wells line its gunwales.",
            "Asura-IIs keep pace with cruisers while hitting like a capital ship, and are favoured as fast-reaction flagships."),
 'neow':   ("A long armoured envelope with no turrets at all: everything that is not a launch tube is armour. Three forward tubes fire heavy torpedoes in salvos, and flare tubes ring the hull.",
            "The Neow cannot raise a shield and does not need one. It sits back, absorbs punishment and reloads its tubes between salvos."),
 'artemis':("A twin-deck catamaran carrier. A catapult rail runs between the two flight decks, with a line of point-defence mounts along each outer rail.",
            "Artemis carriers stay well behind the line and keep a large air wing in the fight."),
 'siren':  ("A wide convertible carrier. In carrier mode its three main guns are folded into silos under the flight deck; converting to battleship mode seals the deck and raises the guns.",
            "The Siren must choose between launching fighters and fighting with its own guns. Its captains switch modes as the range closes."),
 'hastur': ("A battlecruiser made of two parts: an armoured forward hull carrying four twin beam cannons, docked over a spherical command module that houses the hangar and drives.",
            "Hastur crews pair the forward hull's firepower with a small fighter wing, but the ship is vulnerable if enemies get close."),
 'hannibal':("A heavy cruiser with a long armoured snout. A forward battery of energy mounts, one of them tucked under the snout, gives it a strong frontal punch.",
            "A dependable line cruiser used for fire support and escort work."),
 'regulus':("An escort cruiser bristling with small energy mounts and fitted with short-range bubble missile pods at the snout and flanks.",
            "Regulus escorts screen carriers and larger ships from fighters and light craft."),
 'duilius':("A cylindrical cruiser with eight grapple-claw galleries along its flanks and two heavy guns under its bow.",
            "The Duilius closes in and hurls its claws at the target, one of the few cruisers designed for close combat."),
 'abaddon':("A missile cruiser that is little more than an armoured frame, a fighter-style cockpit and two booster bodies wrapped around a single enormous warhead.",
            "The Abaddon exists to deliver one Apocalypse warhead. It carries no shield; flares and armour keep it alive until the launch."),
 'iris':   ("A front-line cruiser carrier with an open flight deck, hangar ramps and a raised stern carrying missile mounts.",
            "Iris carriers act as forward bases for fighter operations but need escorts, as their own defences are light."),
 'selene': ("A fast carrier: a domed hull with two short launch decks on its side pods and a large three-nozzle engine crest.",
            "Selenes are faster than most cruisers and use that speed to keep their wings on the flanks."),
 'fenrir': ("A fast destroyer shaped like an armoured bulb, with a hardpoint in its nose, two short gun mounts on its flanks and a turret on its crown. Its side boosters swivel to vector thrust.",
            "The fastest hull in the line, built for hit-and-run attacks."),
 'hellhound':("A light destroyer shaped like a flashlight: a long armoured handle carrying a gun band and missile ledges, ending in a swivelling lamp-head drive.",
            "Hellhounds hunt damaged ships and finish them off."),
 'garm':   ("An assault destroyer with a tall armoured dome, a heavy gun under its nose and swivelling thruster pods.",
            "Garms charge in, hit a vulnerable target hard and pull out before the enemy can respond."),
}
